name: Release Docker Image

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build-and-push:
    if: github.event.pull_request.merged == true
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Extract Repository Name
        run: echo "REPO_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV
      
      - name: Extract release version
        run: |
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          VERSION=$(echo "$BRANCH_NAME" | sed -nE 's/release\/([0-9]+\.[0-9]+\.[0-9]+)/\1/p')
          if [[ -z "$VERSION" ]]; then
            echo "Error: Could not extract version from branch name."
            exit 1
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/brunovieira003/$REPO_NAME:latest .

      - name: Push Docker Image
        run: |
          docker push ghcr.io/brunovieira003/${{ env.REPO_NAME }}:${{ env.VERSION }}
          docker push ghcr.io/brunovieira003/${{ env.REPO_NAME }}:latest
